"""add_consent_log

Revision ID: 0e4dac089749
Revises: 6087cad81166
Create Date: 2025-12-31 12:30:22.378414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e4dac089749'
down_revision = '6087cad81166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'CLINIC_ADMIN', 'SUPPORT_VIEWER', name='admin_role'), nullable=False),
    sa.Column('mfa_secret', sa.String(length=32), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_last_changed', sa.DateTime(timezone=True), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_admin_active', 'admin_users', ['is_active'], unique=False)
    op.create_index('idx_admin_email', 'admin_users', ['email'], unique=False)
    op.create_index('idx_admin_role', 'admin_users', ['role'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('actor', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=False),
    sa.Column('patient_phone_hash', sa.String(length=64), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor', 'audit_log', ['actor', 'actor_id'], unique=False)
    op.create_index('idx_audit_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_index('idx_audit_patient_hash', 'audit_log', ['patient_phone_hash'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('clinics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_name', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=15), nullable=False),
    sa.Column('subscription_tier', sa.String(length=20), nullable=True),
    sa.Column('subscription_status', sa.String(length=20), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('whatsapp_provider', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_config', sa.JSON(), nullable=True),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_index(op.f('ix_clinics_api_key'), 'clinics', ['api_key'], unique=True)
    op.create_table('clinic_timing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('lunch_enabled', sa.Boolean(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closed_dates',
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('clinic_id', 'closed_date')
    )
    op.create_table('consent_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_source', sa.String(length=20), nullable=False),
    sa.Column('consent_version', sa.String(length=20), nullable=False),
    sa.Column('consent_text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consent_clinic_phone', 'consent_log', ['clinic_id', 'phone'], unique=False)
    op.create_index(op.f('ix_consent_log_phone'), 'consent_log', ['phone'], unique=False)
    op.create_table('doctors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('specialization', sa.String(length=50), nullable=True),
    sa.Column('default_fee', sa.Integer(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('is_searchable', sa.Boolean(), nullable=False),
    sa.Column('custom_availability', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_number')
    )
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_patient_clinic_phone', 'patients', ['clinic_id', 'phone'], unique=True)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('required_slots', sa.Integer(), nullable=False),
    sa.Column('default_fee', sa.Integer(), nullable=False),
    sa.Column('before_buffer_mins', sa.Integer(), nullable=True),
    sa.Column('after_buffer_mins', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinic_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('patient_phone', sa.String(length=15), nullable=False),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('start_utc_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_utc_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appt_clinic_phone', 'appointments', ['clinic_id', 'patient_phone'], unique=False)
    op.create_index('idx_clinic_doctor_date', 'appointments', ['clinic_id', 'doctor_id', 'start_utc_ts'], unique=False)
    op.create_index('idx_doctor_slot_booked_unique', 'appointments', ['doctor_id', 'start_utc_ts'], unique=True, postgresql_where=sa.text("status = 'booked'"))
    op.create_table('doctor_services',
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('custom_fee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'service_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_services')
    op.drop_index('idx_doctor_slot_booked_unique', table_name='appointments', postgresql_where=sa.text("status = 'booked'"))
    op.drop_index('idx_clinic_doctor_date', table_name='appointments')
    op.drop_index('idx_appt_clinic_phone', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('services')
    op.drop_index('idx_patient_clinic_phone', table_name='patients')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_consent_log_phone'), table_name='consent_log')
    op.drop_index('idx_consent_clinic_phone', table_name='consent_log')
    op.drop_table('consent_log')
    op.drop_table('closed_dates')
    op.drop_table('clinic_timing')
    op.drop_index(op.f('ix_clinics_api_key'), table_name='clinics')
    op.drop_table('clinics')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_patient_hash', table_name='audit_log')
    op.drop_index('idx_audit_event_type', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_admin_role', table_name='admin_users')
    op.drop_index('idx_admin_email', table_name='admin_users')
    op.drop_index('idx_admin_active', table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
