"""add_consent_log

Revision ID: 0e4dac089749
Revises: 6087cad81166
Create Date: 2025-12-31 12:30:22.378414

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0e4dac089749'
down_revision = '6087cad81166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Use standard Alembic operations for cross-database compatibility (SQLite/PostgreSQL)
    op.create_table(
        'consent_log',
        sa.Column('id', sa.String(length=36), primary_key=True),
        sa.Column('phone', sa.String(length=15), nullable=False),
        sa.Column('clinic_id', sa.String(length=36), sa.ForeignKey('clinics.id'), nullable=False),
        sa.Column('consent_given', sa.Boolean(), nullable=False),
        sa.Column('consent_source', sa.String(length=20), nullable=False),
        sa.Column('consent_version', sa.String(length=20), nullable=False),
        sa.Column('consent_text', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column('ip_address', sa.String(length=50), nullable=True)
    )
    op.create_index('idx_consent_clinic_phone', 'consent_log', ['clinic_id', 'phone'], unique=False)
    op.create_index(op.f('ix_consent_log_phone'), 'consent_log', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consent_log_phone'), table_name='consent_log')
    op.drop_index('idx_consent_clinic_phone', table_name='consent_log')
    op.drop_table('consent_log')
    # ### end Alembic commands ###
