"""add_upi_id_and_status_to_doctors

Revision ID: 54caccb6b28b
Revises: bbb95cfbd844
Create Date: 2026-01-06 22:12:09.890307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '54caccb6b28b'
down_revision = 'bbb95cfbd844'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_timing',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('lunch_enabled', sa.Boolean(), nullable=True),
    sa.Column('lunch_start', sa.Time(), nullable=True),
    sa.Column('lunch_end', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('closed_dates',
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.Column('closed_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('clinic_id', 'closed_date')
    )
    op.create_table('doctor_services',
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('custom_fee', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('doctor_id', 'service_id')
    )
    op.drop_index('idx_phone_consent_status', table_name='patient_consent')
    op.drop_index('idx_phone_timestamp', table_name='patient_consent')
    op.drop_table('patient_consent')
    op.drop_index('idx_deletion_phone', table_name='patient_deletion_log')
    op.drop_index('idx_deletion_status', table_name='patient_deletion_log')
    op.drop_table('patient_deletion_log')
    op.drop_index('ix_conversations_id', table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('clinic_timings')
    op.drop_index('idx_conversation_expires', table_name='conversation_states')
    op.drop_index('idx_conversation_phone', table_name='conversation_states')
    op.drop_index('idx_conversation_state', table_name='conversation_states')
    op.drop_table('conversation_states')
    op.alter_column('admin_users', 'role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('SUPER_ADMIN', 'CLINIC_ADMIN', 'SUPPORT_VIEWER', name='admin_role'),
               existing_nullable=False)
    op.add_column('appointments', sa.Column('date', sa.DateTime(), nullable=False))
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('appointments', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('idx_appointments_payment_status', table_name='appointments')
    op.drop_index('idx_clinic_phone', table_name='appointments')
    op.drop_index('ix_appointments_id', table_name='appointments')
    op.create_index('idx_appt_clinic_phone', 'appointments', ['clinic_id', 'patient_phone'], unique=False)
    op.drop_column('appointments', 'payment_verified_by')
    op.drop_column('appointments', 'payment_verified_at')
    op.drop_column('appointments', 'receipt_uploaded_at')
    op.drop_column('appointments', 'payment_status')
    op.drop_column('appointments', 'source')
    op.drop_column('appointments', 'receipt_ocr_text')
    op.drop_column('appointments', 'payment_receipt_url')
    op.drop_column('appointments', 'payment_method')
    op.drop_column('appointments', 'payment_amount')
    op.add_column('audit_log', sa.Column('event_id', sa.String(length=100), nullable=False))
    op.add_column('audit_log', sa.Column('event_type', sa.String(length=50), nullable=False))
    op.add_column('audit_log', sa.Column('actor', sa.String(length=50), nullable=False))
    op.add_column('audit_log', sa.Column('actor_id', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('patient_phone_hash', sa.String(length=100), nullable=True))
    op.add_column('audit_log', sa.Column('event_metadata', sa.Text(), nullable=True))
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_index('idx_audit_clinic_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.create_index('idx_audit_event_type', 'audit_log', ['event_type'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.drop_column('audit_log', 'action')
    op.drop_column('audit_log', 'ip_address')
    op.drop_column('audit_log', 'clinic_id')
    op.drop_column('audit_log', 'actor_type')
    op.drop_column('audit_log', 'new_state')
    op.drop_column('audit_log', 'entity_id')
    op.drop_column('audit_log', 'entity_type')
    op.drop_column('audit_log', 'old_state')
    op.drop_column('audit_log', 'actor_reference')
    op.alter_column('clinics', 'owner_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinics', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinics', 'subscription_tier',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinics', 'subscription_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinics', 'whatsapp_provider',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinics', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clinics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('clinics', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('clinics', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index('ix_clinics_id', table_name='clinics')
    op.create_index(op.f('ix_clinics_api_key'), 'clinics', ['api_key'], unique=True)
    op.alter_column('consent_log', 'consent_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('doctors', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('doctors', sa.Column('specialization', sa.String(length=50), nullable=True))
    op.add_column('doctors', sa.Column('default_fee', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('custom_availability', sa.JSON(), nullable=True))
    op.alter_column('doctors', 'clinic_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('doctors', 'upi_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'true'"))
    op.alter_column('doctors', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('doctors', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('idx_doctor_active', table_name='doctors')
    op.drop_index('idx_doctor_searchable', table_name='doctors')
    op.drop_index('idx_doctor_whatsapp', table_name='doctors')
    op.create_foreign_key(None, 'doctors', 'clinics', ['clinic_id'], ['id'])
    op.drop_column('doctors', 'approved_at')
    op.drop_column('doctors', 'whatsapp_number')
    op.drop_column('doctors', 'specialty')
    op.drop_column('doctors', 'accepts_cash')
    op.drop_column('doctors', 'clinic_name')
    op.drop_column('doctors', 'phone')
    op.drop_column('doctors', 'payment_instructions')
    op.drop_column('doctors', 'zelle_email')
    op.drop_column('doctors', 'email')
    op.drop_column('doctors', 'venmo_handle')
    op.drop_column('doctors', 'city')
    op.drop_column('doctors', 'clinic_whatsapp')
    op.drop_column('doctors', 'is_searchable')
    op.drop_column('doctors', 'full_name')
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('ix_patients_id', table_name='patients')
    op.create_index('idx_patient_clinic_phone', 'patients', ['clinic_id', 'phone'], unique=True)
    op.alter_column('services', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'default_fee',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('services', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_index('ix_services_id', table_name='services')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_services_id', 'services', ['id'], unique=False)
    op.alter_column('services', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('services', 'default_fee',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=True)
    op.alter_column('services', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('idx_patient_clinic_phone', table_name='patients')
    op.create_index('ix_patients_id', 'patients', ['id'], unique=False)
    op.alter_column('patients', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.add_column('doctors', sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
    op.add_column('doctors', sa.Column('is_searchable', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False))
    op.add_column('doctors', sa.Column('clinic_whatsapp', sa.VARCHAR(length=15), nullable=True))
    op.add_column('doctors', sa.Column('city', sa.VARCHAR(length=100), nullable=True))
    op.add_column('doctors', sa.Column('venmo_handle', sa.VARCHAR(length=255), nullable=True))
    op.add_column('doctors', sa.Column('email', sa.VARCHAR(length=100), nullable=True))
    op.add_column('doctors', sa.Column('zelle_email', sa.VARCHAR(length=255), nullable=True))
    op.add_column('doctors', sa.Column('payment_instructions', sa.TEXT(), nullable=True))
    op.add_column('doctors', sa.Column('phone', sa.VARCHAR(length=15), nullable=True))
    op.add_column('doctors', sa.Column('clinic_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('doctors', sa.Column('accepts_cash', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False))
    op.add_column('doctors', sa.Column('specialty', sa.VARCHAR(length=100), nullable=True))
    op.add_column('doctors', sa.Column('whatsapp_number', sa.VARCHAR(length=20), nullable=False))
    op.add_column('doctors', sa.Column('approved_at', sa.DATETIME(), nullable=True))
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_index('idx_doctor_whatsapp', 'doctors', ['whatsapp_number'], unique=False)
    op.create_index('idx_doctor_searchable', 'doctors', ['is_searchable', 'city'], unique=False)
    op.create_index('idx_doctor_active', 'doctors', ['is_active'], unique=False)
    op.alter_column('doctors', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('doctors', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('doctors', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'true'"))
    op.alter_column('doctors', 'upi_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('doctors', 'clinic_id',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('doctors', 'custom_availability')
    op.drop_column('doctors', 'default_fee')
    op.drop_column('doctors', 'specialization')
    op.drop_column('doctors', 'name')
    op.alter_column('consent_log', 'consent_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_clinics_api_key'), table_name='clinics')
    op.create_index('ix_clinics_id', 'clinics', ['id'], unique=False)
    op.alter_column('clinics', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('clinics', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('clinics', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('clinics', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinics', 'whatsapp_provider',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinics', 'subscription_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinics', 'subscription_tier',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinics', 'timezone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clinics', 'owner_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('audit_log', sa.Column('actor_reference', sa.VARCHAR(length=100), nullable=False))
    op.add_column('audit_log', sa.Column('old_state', sqlite.JSON(), nullable=True))
    op.add_column('audit_log', sa.Column('entity_type', sa.VARCHAR(length=50), nullable=False))
    op.add_column('audit_log', sa.Column('entity_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('audit_log', sa.Column('new_state', sqlite.JSON(), nullable=True))
    op.add_column('audit_log', sa.Column('actor_type', sa.VARCHAR(length=20), nullable=False))
    op.add_column('audit_log', sa.Column('clinic_id', sa.VARCHAR(length=36), nullable=False))
    op.add_column('audit_log', sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True))
    op.add_column('audit_log', sa.Column('action', sa.VARCHAR(length=50), nullable=False))
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_event_type', table_name='audit_log')
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_clinic_timestamp', 'audit_log', ['clinic_id', 'timestamp'], unique=False)
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.drop_column('audit_log', 'event_metadata')
    op.drop_column('audit_log', 'patient_phone_hash')
    op.drop_column('audit_log', 'actor_id')
    op.drop_column('audit_log', 'actor')
    op.drop_column('audit_log', 'event_type')
    op.drop_column('audit_log', 'event_id')
    op.add_column('appointments', sa.Column('payment_amount', sa.NUMERIC(precision=10, scale=2), nullable=True))
    op.add_column('appointments', sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True))
    op.add_column('appointments', sa.Column('payment_receipt_url', sa.TEXT(), nullable=True))
    op.add_column('appointments', sa.Column('receipt_ocr_text', sa.TEXT(), nullable=True))
    op.add_column('appointments', sa.Column('source', sa.VARCHAR(length=20), server_default=sa.text("'whatsapp'"), nullable=True))
    op.add_column('appointments', sa.Column('payment_status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=False))
    op.add_column('appointments', sa.Column('receipt_uploaded_at', sa.DATETIME(), nullable=True))
    op.add_column('appointments', sa.Column('payment_verified_at', sa.DATETIME(), nullable=True))
    op.add_column('appointments', sa.Column('payment_verified_by', sa.VARCHAR(length=36), nullable=True))
    op.drop_index('idx_appt_clinic_phone', table_name='appointments')
    op.create_index('ix_appointments_id', 'appointments', ['id'], unique=False)
    op.create_index('idx_clinic_phone', 'appointments', ['clinic_id', 'patient_phone'], unique=False)
    op.create_index('idx_appointments_payment_status', 'appointments', ['payment_status'], unique=False)
    op.alter_column('appointments', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('appointments', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('appointments', 'doctor_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('appointments', 'date')
    op.alter_column('admin_users', 'role',
               existing_type=sa.Enum('SUPER_ADMIN', 'CLINIC_ADMIN', 'SUPPORT_VIEWER', name='admin_role'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.create_table('conversation_states',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('current_state', sa.VARCHAR(length=30), server_default=sa.text("'initial'"), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('last_message_at', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('consent_granted', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('age_verified', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index('idx_conversation_state', 'conversation_states', ['current_state'], unique=False)
    op.create_index('idx_conversation_phone', 'conversation_states', ['phone_number'], unique=False)
    op.create_index('idx_conversation_expires', 'conversation_states', ['expires_at'], unique=False)
    op.create_table('clinic_timings',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('clinic_id', sa.VARCHAR(), nullable=False),
    sa.Column('day_of_week', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('slot_duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('clinic_id', sa.VARCHAR(), nullable=False),
    sa.Column('patient_id', sa.VARCHAR(), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(), nullable=False),
    sa.Column('current_step', sa.VARCHAR(), nullable=False),
    sa.Column('context', sqlite.JSON(), nullable=True),
    sa.Column('last_message_at', sa.DATETIME(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversations_id', 'conversations', ['id'], unique=False)
    op.create_table('patient_deletion_log',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('deletion_requested_at', sa.DATETIME(), nullable=False),
    sa.Column('deletion_completed_at', sa.DATETIME(), nullable=True),
    sa.Column('deletion_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('patient_records_deleted', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('appointment_records_deleted', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('consent_records_deleted', sa.INTEGER(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('requested_by', sa.VARCHAR(length=20), nullable=False),
    sa.Column('verification_method', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deletion_status', 'patient_deletion_log', ['deletion_status'], unique=False)
    op.create_index('idx_deletion_phone', 'patient_deletion_log', ['phone_number'], unique=False)
    op.create_table('patient_consent',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=15), nullable=False),
    sa.Column('consent_text', sa.VARCHAR(), nullable=False),
    sa.Column('consent_version', sa.VARCHAR(length=50), nullable=False),
    sa.Column('consent_status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=50), nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), server_default=sa.text("'whatsapp'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_phone_timestamp', 'patient_consent', ['phone_number', 'timestamp'], unique=False)
    op.create_index('idx_phone_consent_status', 'patient_consent', ['phone_number', 'consent_status'], unique=False)
    op.drop_table('doctor_services')
    op.drop_table('closed_dates')
    op.drop_table('clinic_timing')
    # ### end Alembic commands ###
